### ISSUE TITLE
Countdown timer doesn't work

### ISSUE THREAD

**Issue by raquelxmoss** [heisenburger/thingsofinterest#1]
What I did:

Pushed the play button on the latest episode

What I expected:

For the 'countdown' timer on the right-hand side to tell me how much longer I had to go in the episode.

What happened:

Countdown timer stayed at 00:00 😭 

Details:

Chrome, latest

<img width="683" alt="screen shot 2016-07-08 at 4 29 19 pm" src="https://cloud.githubusercontent.com/assets/7959274/16677386/60d9033a-4529-11e6-85bd-aa7e13e61f6d.png">

**Comment by heisenburger** [comment]
The time on the right is just supposed to display the duration, not countdown, but it definitely shouldn't be displaying 00:00 😕

I'm also on the latest Chrome on Mac. Here's what I see:

![image](https://cloud.githubusercontent.com/assets/6912474/16678062/c4a15b96-452f-11e6-88f6-351eb41a0949.png)

Does your console show any javascript errors?

You're also supposed to see a progress bar like the one in my screenshot above. Hmm. Curious.

**Comment by raquelxmoss** [comment]
That's weird, it's working now, no problems. If I see it again, I'll check for console errors!

**Comment by heisenburger** [comment]
Hmm, it could be very likely you saw an unfinished version of the site — I've got Cloudfront running so updates take a while to roll through to everyone.

Thanks for bringing it up 😘

**Comment by heisenburger** [comment]
I've just spotted this now. Looking into it.

**Comment by heisenburger** [comment]
Closing this because I cannot replicate it at all...
