### ISSUE TITLE
Show notes not acting as expected?

### ISSUE THREAD

**Issue by raquelxmoss** [heisenburger/thingsofinterest#2]
I was listening to your podcast and you mentioned that you would put a link in the show notes. So I clicked on the show notes, and the link text and colour changed, but nothing else happened 😞 . Latest Chrome, OSX.

<img width="641" alt="screen shot 2017-05-30 at 8 22 33 pm" src="https://cloud.githubusercontent.com/assets/7959274/26574564/e9e428c4-4575-11e7-8b87-6f17b8611920.png">
<img width="669" alt="screen shot 2017-05-30 at 8 22 26 pm" src="https://cloud.githubusercontent.com/assets/7959274/26574565/e9fa205c-4575-11e7-9177-3a7628cdcf7e.png">

**Comment by heisenburger** [comment]
Hehe good catch! Nothing is broken here — we've just been slack on our shownotes 😂😂😂
